### ISSUE TITLE
请问可以写一个requirements文档吗？

### ISSUE THREAD

**Issue by 177715031** [epcm/QtNoGo#1]

**Comment by epcm** [comment]
你好，本项目使用Qt 5.15.2编译，没有依赖Qt之外的c++库
1. 如果你只是想本地运行，请下载releases中v1压缩包，解压后安装字体文件，运行NoGo.exe即可
2. 如果你想在本地编译，请下载Qt5，在Qt中打开该项目并编译

**Comment by 177715031** [comment]
E:\QtNoGo-master\ai\aimcts.cpp:50: error: C2039: “dfsAir”: 不是“Node”的成员
E:\QtNoGo-master\ai\aimcts.h:13: 参见“Node”的声明
E:\QtNoGo-master\ai\aimcts.cpp:59: error: C2065: “current_board”: 未声明的标识符
E:\QtNoGo-master\ai\aimcts.cpp:59: error: C2065: “current_board”: 未声明的标识符
E:\QtNoGo-master\ai\aimcts.cpp:115: error: C2447: “{”: 缺少函数标题(是否是老式的形式表?)
等等一些error，不知道怎么回事

**Comment by epcm** [comment]
请提供更为详细的报错信息，以及Qt版本，Qt构建设置，操作系统版本等信息
不过很抱歉，最近在忙期末考试，具体测试和回复可能要在7月3日之后

**Comment by 177715031** [comment]
大佬，请问可以给一个邮箱吗？我是软件工程专业的，以后有什么问题也想请教请教您。

**Comment by epcm** [comment]
邮箱已经更新在主页，感谢关注
不过我只是计算机系的大一学生，大概率知识水平不足以回答你的问题

**Comment by 177715031** [comment]
请问这个使用MCTS了，还有什么手段可以提升这个AI的实力呢？

**Comment by epcm** [comment]
https://ieeexplore.ieee.org/abstract/document/6145622
建议参考这篇文献

**Comment by 177715031** [comment]
![image](https://user-images.githubusercontent.com/70942569/123957244-21ebca00-d9de-11eb-94fa-6b5872e06bee.png)

**Comment by 177715031** [comment]
并没有找到你的ico文件

**Comment by 177715031** [comment]
你好，以前的问题已经全部解决了，现在发现了一个新问题，再AI思考是过长的情况下，20s，会爆内存，terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
应该怎样处理呢？

**Comment by epcm** [comment]
这个ai是以1s计算时间为基准进行设计和优化的
爆内存的话，可以考虑延迟创建节点，即在一个节点在被访问指定次数后，再从这个节点开始进行expand，上面的论文中应该有讲这个问题
以及能否说一下之前的报错是什么原因，怎么解决的呢？

**Comment by 177715031** [comment]
1.之前的报错是因为ico文件找不到了，知道在.pro中把.ico的配置删除即可。
2.AI以1s为基准大概只能搜索4w次，AI的实力还是没办法更上一个层次，延迟扩展的话本质上也是减少了扩展次数，和减少访问时间差不多，在不减少搜索时间的条件下，搜索更多的次数，还要解决内存泄漏，个人觉得可以把泄露的地方free了，但是我发现无论在16G还是在32G的条件下运行，都会泄露，说明泄露的太多了，第二种方法，我觉得可以用内存池，boost.pool。但是我使用内存池的时候，程序直接死了，不知道什么原因，可以一起研究一下吗?或者还有什么比较好的办法吗？

**Comment by epcm** [comment]
非常感谢你的反馈！
1. 这个AI只是为了botzone平台对战编写，其时间限制为1s，故设计时并没有考虑长时情况
2. 很抱歉我内存管理方面知识比较匮乏，设计时没有考虑泄漏问题，可能这方面也帮不太上忙
